Remove prefix remove suffix
biopython/biopython pull request #3335
Opened 2020-11-03 11:38 UTC by Benedict-Carling

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3299 

Adds new python 3.9 str functions to Seq object, removeprefix and remove suffix

New Functionality

```python
>>> from Bio.Seq import Seq
>>> my_seq = Seq("ATGGTGTGTGT")
>>> my_seq
Seq('ATGGTGTGTGT')
>>> my_seq.removeprefix('ATG')
Seq('GTGTGTGT')
```

New functions can also take argument at a Seq Object

```python
>>> from Bio.Seq import Seq
>>> my_seq = Seq("GTGTGTGTTAG")
>>> my_seq
Seq('GTGTGTGTTAG')
>>> stop_codon = Seq("TAG")
>>> my_seq.removesuffix(stop_codon)
Seq('GTGTGTGT')
```

Unit Tests are added to confirm this functionality

Thanks for looking at my first pull request here 👋 im looking forward to contributing more,
Benedict

2020-11-03 15:00 UTC, peterjc requested changes
Thank you for working on this. With some slight changes this looks good (see in line comments). I also think this deserves a mention in the NEWS file.

Note: If #3333 gets merged first, this will need some additional work. I had not anticipated that when I opened #3299 for adding this functionality.

2020-11-03 17:49 UTC, peterjc commented on Bio/Seq.py
> +                if str(self).startswith(str(prefix)):
You don't need ``str(prefix)`` now, just ``prefix`` is enough.

2020-11-03 17:49 UTC, peterjc commented on Bio/Seq.py
> +                if str(self).endswith(str(suffix)):
Again, just ``suffix`` rather than ``str(suffix)``

2020-11-03 17:51 UTC, peterjc commented
One remaining small tweak aside (remove two now redundant calls to ``str(...)``, see code comments), this looks good to me.

@mdehoon could you review, and can we merge this before #3333?

2020-11-03 19:13 UTC, peterjc approved these changes

2020-11-04 05:35 UTC, mdehoon commented
> @mdehoon could you review, and can we merge this before #3333?

This code will change after #3333 gets in, so it makes more sense to do #3333 first.

2020-11-27 12:50 UTC, peterjc commented
This will need updating now that bytes are used internally.

2020-12-03 14:54 UTC, peterjc commented
@Benedict-Carling do you need help updating this for the recent bytes changes? Or should one of us update the pull request (we'll still credit you of course)?

2020-12-03 14:54 UTC, peterjc requested changes
Needs updating for bytes work on the Seq class.

2021-06-08 09:47 UTC, peterjc commented
I've rebased this and attempted to update it for the major ``Seq`` objects changes.

2021-11-02 11:25 UTC, peterjc commented
TravisCI was failing (some kind of time out), but in any case we've since migrated to GitHub Actions.

Any reason not to rebase this and see how the tests look now?

2022-01-06 12:01 UTC, peterjc commented
Reopened, rebased, more tests, and now considers ``UnknownSeq`` explicitly.

2022-01-06 12:18 UTC, peterjc commented
CI failed on Linux due to #3834

2023-05-19 11:28 UTC, peterjc approved these changes

2023-05-20 07:07 UTC, mdehoon approved these changes

2023-05-22 11:08 UTC, peterjc commented
Thank you both, merging...

2023-05-22 11:08 UTC, merged