Add __slots__ to sequence objects
biopython/biopython pull request #3482
Opened 2021-02-15 03:23 UTC by mdehoon

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Following up on issue #2854 .

This PR adds slots to `SequenceDataAbstractBaseClass`, `_SeqAbstractBaseClass`, `Seq`, `MutableSeq`, `_UndefinedSequenceData`, `_TwoBitSequenceData`, and `_BioSQLSequenceData`.

This reduces the memory overhead of a `Seq` object from 239 bytes to 40 bytes, as assessed using the get_size function:

```python
import sys

def get_size(obj, seen=None):
    """Recursively finds size of objects"""
    size = sys.getsizeof(obj)
    if seen is None:
        seen = set()
    obj_id = id(obj)
    if obj_id in seen:
        return 0
    # Important mark as seen *before* entering recursion to gracefully handle
    # self-referential objects
    seen.add(obj_id)
    if isinstance(obj, dict):
        size += sum([get_size(v, seen) for v in obj.values()])
        size += sum([get_size(k, seen) for k in obj.keys()])
    elif hasattr(obj, '__dict__'):
        size += get_size(obj.__dict__, seen)
    elif hasattr(obj, '__iter__') and not isinstance(obj, (str, bytes, bytearray)):
        size += sum([get_size(i, seen) for i in obj])
    return size
```

For backward compatibility, to still allow users to use attributes on `Seq` objects, `__setattr__`, `__getattr__`, and `__delattr__` methods are provided on `_SeqAbstractBaseClass` which store attributes together with the sequence data under `_data`.

2021-02-15 09:43 UTC, peterjc requested changes
This seems overly complicated, and needs code documentation if you are set on this design. Also some explicit tests would be wise.

Can a private ``._attributes`` dictionary be used, even if it does not have quite such a good memory saving?

2021-02-15 15:45 UTC, mdehoon commented
Using `transmalloc` to measure memory usage with this script:

```python
import tracemalloc
from Bio.Seq import Seq

n = 100000
tracemalloc.start()
sequences = [Seq("") for i in range(n)]
current, peak = tracemalloc.get_traced_memory()
usage = int(round(peak / n))
print("memory usage is %d bytes per object" % usage)
tracemalloc.stop()
```
gives the following:

- current master: 160 bytes
- first version of this PR: 48 bytes
- with a private `_attributes` dictionary: 56 bytes
- current version of this PR: 64 bytes

2021-02-15 15:47 UTC, peterjc commented
This version looks far more elegant 👍

2021-02-15 16:18 UTC, peterjc requested changes
This looks far easier to understand now, even if not quite as much memory is saved. Approval in principle 👍 

I would still like to see a test adding, reading, and deleting a run time attribute to an instance of each of the main sequence classes.

2021-02-16 08:32 UTC, peterjc approved these changes
Looks good. Don't forget we still need a general update to the NEWS file for the sequence work, unless you have more planned soon should we do the release?

2021-02-16 12:06 UTC, merged

2021-02-16 12:14 UTC, mdehoon commented
@peterjc  I think this is a good time to do a release.