replace isinstance(int) by isinstance(numbers.Integral)
biopython/biopython pull request #3642
Opened 2021-06-26 00:30 UTC by mdehoon

See issue #3641 .`isinstance(x, int)` will return `False` if x is an integer other than a Python plain integer, e.g. a numpy integer. This PR replaces `isinstance(x, int)` by `isinstance(x, numbers.Integral)` for a few obvious cases, including `Seq` and `SeqRecord`. This is useful for the slicing & indexing code in `Bio.Align`, where the alignment coordinates are stored in a numpy array of integers.

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

2021-06-27 21:35 UTC, peterjc requested changes
Add a couple of tests for slicing these with a numpy integer and it looks good.

2021-06-28 13:04 UTC, peterjc approved these changes

2021-06-28 13:05 UTC, peterjc commented
There are still some teething issues with GitHub actions, the PyPy3 and Windows failures look irrelevant.

2021-06-28 13:08 UTC, mdehoon commented
Thanks!

2021-06-28 13:08 UTC, merged