Fabianegli query pop
biopython/biopython pull request #3660
Opened 2021-07-07 15:31 UTC by fabianegli

- [x] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [x] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [x] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3604

2021-07-07 16:16 UTC, fabianegli commented
I don't get why codecov reports a test coverage decrease when clearly no code was added, but two tests were. Can someone enlighten me?

2021-07-07 17:13 UTC, peterjc commented
We see small fluctuations in CodeCov values normally, likely a sign of stochastic branches and/or random test data.

This case could be a side effect of our transition from TravisCI to GitHub actions (were right now I think less dependencies are setup, and thus less code gets tested)

2021-07-09 20:36 UTC, bow requested changes
@fabianegli Thanks for opening this MR :+1: ~ I only have minor comments related to spelling, back to you.

2021-07-09 20:36 UTC, bow commented on Tests/test_SearchIO_model.py
> +        hit = self.qresult.pop(inexistent_key, default)
```suggestion
    def test_pop_nonexistent_with_default(self):
        """Test QueryResult.pop with default for nonexistent key."""
        default = "An arbitrary default return value for this test only."
        nonexistent_key = "neither a standard nor alternative key"
        hit = self.qresult.pop(nonexistent_key, default)
```

2021-07-09 20:36 UTC, bow commented on Tests/test_SearchIO_model.py
> +        self.assertRaises(KeyError, self.qresult.pop, inexistent_key)
```suggestion
    def test_pop_nonexistent_key(self):
        """Test QueryResult.pop with default for nonexistent key."""
        nonexistent_key = "neither a standard nor alternative key"
        self.assertRaises(KeyError, self.qresult.pop, nonexistent_key)
```

2021-07-12 10:19 UTC, fabianegli commented
@bow Thanks for the review and all your input!

2021-07-13 14:41 UTC, bow commented
@fabianegli Thanks for pushing the changes ~ looks good to me now and have added my approval :).

@peterjc I can see test failures but they seem to be unrelated to the changes made in this MR. Are there any changes from `master` that should be merged back in, or are those failures intermittent?

2021-07-13 19:23 UTC, peterjc commented
There are some known glitches related to adopting GitHub actions (or just coincidental in timing) like #3640 and #3659

2021-11-25 12:26 UTC, fabianegli commented
Now that the test coverage calculation issue has been resolved in the repo this is probably ready to be merged?

2021-11-25 17:18 UTC, bow commented
@fabianegli I believe so :+1: ~ let's go ahead with this.

2021-11-25 17:18 UTC, merged