bugfix for writing genpept with long ids.
biopython/biopython pull request #3733
Opened 2021-09-16 16:02 UTC by seanrjohnson

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit`` locally,
and understand that AppVeyor and TravisCI will be used to confirm the Biopython unit
tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3732 

One line change as suggested in the issue post, plus a test.

2022-10-18 09:17 UTC, mdehoon requested changes
Instead of commenting out lines, just remove them.

2022-10-18 10:58 UTC, peterjc commented
Why are you removing all those warnings anyway?

2022-10-18 13:20 UTC, seanrjohnson commented
> Why are you removing all those warnings anyway?

That's a good question. Actually I didn't mean those last few commits to be part of the pull request (didn't realize, or maybe forgot, that Github updates pull requests with later commits to the same branch, I should have made a new branch for those).

But to answer your question, I was trying to optimize the speed of the genbank parser, so I did profiling and found that those lines cause major performance hits and check for very rare conditions.

I'll try to revert the branch back to the commit that I intended to include.

2022-10-18 13:33 UTC, peterjc commented
Yes, updating the branch updates the pull request too. Very useful once you know to expect this.

I wondered if the de-quoting change from regex to plain Python would be good or bad from a performance point of view. Avoiding the regex would be easier to read.

2022-10-18 13:45 UTC, seanrjohnson commented
avoiding the regexes is helpful for speed. The changes in that commit are all the result of profiling I did. All together the changes almost halve the parsing time (9 seconds to 5 seconds for the example I was profiling on).

2022-10-18 14:02 UTC, peterjc commented
It has been years since I last profiled the GenBank parser, I guess we've built up some additional checks which come at a speed cost. Hopefully we can speed them up now you've flagged some hotspots.

2022-10-18 14:02 UTC, seanrjohnson commented
I made a commit reverting changes irrelevant for this pull request (except the one changing the quotes regex to checking the first and last characters). Sorry for the confusion.

2022-10-18 14:04 UTC, peterjc commented
Note you've accidentally deleted the symlink ``LICENSE`` here.

Feel free to clean up the branch history (e.g. ``git rebase`` into a single commit), but if not we can do a squash-and-merge of this pull request instead.

2022-10-18 14:19 UTC, seanrjohnson commented
Ok, I tried. The history looks even more complicated now, so not sure if I did it right.

2022-10-18 14:24 UTC, peterjc commented
The history looks cleaner now (no merges). If you're not familiar with git-rebase, it isn't immediately obvious how to use it to combine commits and re-write the commit messages. Don't worry about it.

We can squash-and-merge with a commit comment about speeding up the quote removal, and addressing the false positive warning for #3732.

2022-10-18 15:25 UTC, seanrjohnson commented on Bio/GenBank/__init__.py
> +        if (value[0] == '"') and (value[-1] == '"'):
I suppose `if len(value) > 1 and value[0] == '"' and value[-1] == '"'`
would address all of those concerns without new weird side effects?

2022-10-18 18:28 UTC, peterjc commented on Bio/GenBank/__init__.py
> +        if (value[0] == '"') and (value[-1] == '"'):
Pythonic style would be checking non-zero ``value`` by treating it as a boolean: ``if value and value[0] == '"' and value[-1] == '"':``

But yes, that's the simplest/safest change I could come up with too.

2022-10-18 18:29 UTC, peterjc commented on Bio/GenBank/__init__.py
> +        if (value[0] == '"') and (value[-1] == '"'):
P.S. I'm pleased to see the test suite caught this, ``IndexError: string index out of range``

2022-10-18 20:41 UTC, seanrjohnson commented on Bio/GenBank/__init__.py
> +        if (value[0] == '"') and (value[-1] == '"'):
ok, I made that change.

2022-10-19 13:16 UTC, seanrjohnson commented on Bio/GenBank/__init__.py
> +        if (value[0] == '"') and (value[-1] == '"'):
@peterjc 
I just ran the benchmark again, and just that one change still seems to speed it up a bit.
My test file takes 9.1 seconds to parse with the `value = re.sub('^"|"$', "", value)`. but when I change to `if len(value) > 1 and value[0] == '"' and value[-1] == '"'` it goes down to 7.7 seconds.

2022-10-21 13:28 UTC, peterjc commented on Bio/GenBank/__init__.py
> +        if (value[0] == '"') and (value[-1] == '"'):
Nice 🚀

2022-10-21 13:54 UTC, merged