Gene
biopython/biopython pull request #3835
Opened 2022-01-05 18:45 UTC by vishesh2802

As discussed on #3831, addition is straight-forward, but subtraction is roundabout: `loc + (-5)` instead of `loc - 5`. In this PR, I added the` __sub__` feature to workaround `feature + (-5)` instead of `feature - 5`.

- [ ] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [ ] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Closes #3831

2022-01-06 10:27 UTC, peterjc commented on Bio/SeqFeature.py
> +        """Subtracting an integer will give a new FeatureLocation with
This docstring needs to start with a one line summary ending with a full stop, then a blank link. See PEP257 and the associated checks for this in flake8.

2022-01-06 10:30 UTC, peterjc requested changes
This is looking much better that the first PR, but will still need tests added.

2022-01-06 10:30 UTC, peterjc commented on Bio/SeqFeature.py
> +        >>> print(f1)
The example needs to be self contained, so should start by defining the feature.

2022-01-06 10:30 UTC, peterjc commented on Bio/SeqFeature.py
> +        [-195:-190]
These examples are showing the work around of adding negative numbers. You can show ``f1  + (-100)`` does, but should focus on what ``f1 - 100`` does.

2022-01-16 10:40 UTC, peterjc commented on Bio/SeqFeature.py
> +        >>> print(f1)
The ``from Bio.SeqFeature import FeatureLocation`` line needs the ``>>> `` (or can be left out).

2022-01-16 10:41 UTC, peterjc commented on Bio/SeqFeature.py
> +        TypeError: unsupported operand type(s) for -: 'FeatureLocation' and 'int'
The ``TypeError`` is unexpected.

You should make a feature with large location values like 105-150, and then when subtracting 100 your feature should be location 5-50 instead.

2022-01-17 09:29 UTC, peterjc commented
Well done, the code change and the docstring looks good now.

I can't spot why by eye, but the code formatting tool black would make changes.

This still needs some tests though (including checking subtracting a non-integer gives a sensible answer).

2022-01-17 11:53 UTC, vishesh-soni commented
Okay, and the bot will do the test or I should do it.

2022-01-17 12:37 UTC, peterjc commented
The continuous integration (GitHub Actions, AppVeyor, etc) will *run* the tests.

I would like you to *write* some new tests (and run them on your machine too), probably in file ``Tests/test_SeqFeature.py``

2022-01-18 19:44 UTC, vishesh-soni commented
Yeah, but I want you to assign me an issue that you feel would be compatible with me.

2022-02-09 14:49 UTC, peterjc commented
There was trailing white space in the Python code, that was why the style checks failed. I also added something to the test suite.

2022-02-09 15:37 UTC, peterjc commented
See #3752 for the coverage fluctuations.

@MarkusPiotrowski or @mdehoon could you review this please? I'd like to "rebase and merge" to keep the authorship record.

2022-09-13 08:40 UTC, peterjc commented
I think this still makes sense even with #4063 although which ever is merged first, the other would need some minor updates.

2022-09-13 11:14 UTC, mdehoon approved these changes

2022-09-13 13:56 UTC, merged