Numpy standardize
biopython/biopython pull request #4258
Opened 2023-03-10 00:49 UTC by pvalle6

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed. (*This acknowledgement is optional.*)

Updated Celfile.py, bed.py, sam.py, __init__.py with #4238 reccomendations

2023-03-10 12:30 UTC, peterjc commented on Bio/Align/__init__.py
> +        ...                       coordinates = np.array([[0, 2, 3, 5],
Can you also fix the following two lines to change their indentation to match?

2023-03-10 12:32 UTC, peterjc requested changes
One minor formatting change requested in the docstring example.

Unless you wanted to rebase this, I'd go with a squash-and-merge for a simpler commit history.

Over to @mdehoon to comment...

2023-03-10 13:17 UTC, mdehoon approved these changes

2023-03-10 18:07 UTC, pvalle6 commented
> One minor formatting change requested in the docstring example.
> 
> Unless you wanted to rebase this, I'd go with a squash-and-merge for a simpler commit history.
> 
> Over to @mdehoon to comment...

Completely agree, I'll update when I get to PC

2023-04-23 21:50 UTC, peterjc approved these changes
I fixed the indentation, good to squash-and-merge once tests finish running.

2023-04-23 23:28 UTC, merged

2023-04-23 23:29 UTC, peterjc commented
Merged, thank you!