Standardize on import numpy as np
biopython/biopython pull request #4259
Opened 2023-03-10 18:32 UTC by BabaYaga1221

- [X] I hereby agree to dual license this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [ ] I have added my name to the alphabetical contributor's listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, are listed
already or do not wish to be listed. (*This acknowledgment is optional.*)

Closes #...
Update the ``import numpy`` with the ``import numpy as np`` standard.

2023-03-11 07:23 UTC, peterjc commented on Bio/Affy/CelFile.py
> -        "Install NumPy if you want to use Bio.Affy.CelFile"
NumPy is how the project capitalises their name. Don't change this.

2023-03-11 07:26 UTC, peterjc commented
Duplicates work already in progress on #4258, will look again once that's merged and this has been black formatted.

Also note this updates a lot of the tests despite discussion on #4238 about concerns for the ``test_Align*.py`` files in particular.

2023-03-11 08:20 UTC, BabaYaga1221 commented
Ok, Sure. Take your time sir.

2023-03-16 17:03 UTC, BabaYaga1221 commented
Okay, @peterjc I will inform you as soon as possible.

2023-03-16 19:31 UTC, BabaYaga1221 commented
@peterjc revert all the changes on ``Test/test_Align*.py`` files.

2023-03-17 17:49 UTC, peterjc commented on Bio/PDB/vectors.py
> +    """Generate a 4x4 np scaling matrix.
NumPy for the docstring, not np

2023-03-17 17:49 UTC, peterjc commented on Bio/PDB/vectors.py
> +    :param array xyz: column vector (3 row x 1 column np array)
NumPy for the docstring, not np

2023-03-17 17:51 UTC, peterjc commented on Tests/test_MarkovModel.py
> -    from numpy import log
I don't think you needed to change any of these imports - maybe just revert all the changes to this file?

2023-03-17 17:53 UTC, peterjc commented on Bio/LogisticRegression.py
> +# import np.linalg
I think you can remove this comment.

(I'm assuming this still works - there probably was once a reason to explicitly import linalg)

2023-03-17 17:55 UTC, peterjc commented on Bio/SVDSuperimposer/__init__.py
> -    from numpy import dot, transpose, sqrt
This was not on the list of things we suggested changing. I would be inclined not to touch this since you've left it with inconsistent import styles.

2023-03-17 17:57 UTC, peterjc commented
I really should have been more explicit in writing #4238. Even with most of the test changes removed this is far to long for easy review. I've noted some points though.

2023-03-17 18:12 UTC, BabaYaga1221 commented
Okay Sir, @peterjc, I will note your work and update the status as soon as possible.

2023-03-18 17:54 UTC, peterjc commented
It looks like you accidentally checked in lots of files under ``Tests/__pycache__/`` and then deleted them again?

2023-03-18 17:56 UTC, BabaYaga1221 commented
It was a mistake, I accidentally created some unnecessary files. That's why, I delete them all in next commit

2023-03-18 17:58 UTC, peterjc commented on Bio/Cluster/__init__.py
> +       2. a 1D Numpy array containing the distances consecutively;
If changing numpy in the text, use NumPy not Numpy.

(4 cases in this file, lines 191, 193, 281 and 283)

2023-03-18 18:09 UTC, peterjc approved these changes
Long, but by eye all the changes look good and I see no formatting issues now (after dropped changes to most of the test files especially, those currently with black-exempt regions).

2023-03-18 18:10 UTC, peterjc commented
Note when merging - this should be a squash-and-merge because the history has some mis-steps.

2023-03-18 18:10 UTC, peterjc commented
Oh, an issue:

```
Bio/MarkovModel.py:39:11: F821 undefined name 'numpy'
```

2023-03-18 18:11 UTC, peterjc requested changes
Please fix ``Bio/MarkovModel.py:39:11: F821 undefined name 'numpy'``

2023-03-18 18:15 UTC, BabaYaga1221 commented
@peterjc okay sir, i will resolve issue and commit again.

2023-03-22 16:53 UTC, BabaYaga1221 commented
@peterjc Sir, would you like to review the latest commit?

2023-03-22 18:44 UTC, peterjc approved these changes

2023-03-22 18:46 UTC, peterjc reviewed
As noted earlier, much longer (more changes) than I would have liked to review in one pull request - but this looks good now to squash-and-merge.

Given the length, a second review would be sensible. @mdehoon?

2023-03-22 18:46 UTC, peterjc approved these changes

2023-03-22 20:46 UTC, mdehoon approved these changes

2023-03-23 09:37 UTC, merged

2023-03-23 09:37 UTC, peterjc commented
Thank you!

2023-03-23 12:07 UTC, BabaYaga1221 commented
@peterjc Pleasure to work on this project, Sir. In near future, I will try to contribute more enhancement in biopython.