Add SearchIO.InfernalIO module
biopython/biopython pull request #4874
Opened 2024-10-25 14:30 UTC by drs

- [X] I hereby agree to dual licence this and any previous contributions under both
the _Biopython License Agreement_ **AND** the _BSD 3-Clause License_.

- [X] I have read the ``CONTRIBUTING.rst`` file, have run ``pre-commit``
locally, and understand that continuous integration checks will be used to
confirm the Biopython unit tests and style checks pass with these changes.

- [X] I have added my name to the alphabetical contributors listings in the files
``NEWS.rst`` and ``CONTRIB.rst`` as part of this pull request, am listed
already, or do not wish to be listed.

Add an Infernal search results parser and indexer. This parser handles plain text and tabular output. For tabular output, formats 1 (default), 2 and 3 are supported.

2024-10-25 15:39 UTC, peterjc commented
This will deserve a ``NEWS.rst`` entry.

Test failures with ``ModuleNotFoundError: No module named 'Bio.SearchIO.InfernalIO'``, you will need to manually add it to the package list in our ``setup.py`` (updating the packaging is something we ought to look at separately).

2024-10-25 17:03 UTC, drs commented
I fixed the `setup.py` and added the contribution in `NEWS.rst`.

2024-10-28 09:41 UTC, peterjc commented on NEWS.rst
> +- Samuel Prince (first contribution)
This should be alphabetical by first name, although it looks like that needs fixing anyway.

2024-10-28 09:45 UTC, peterjc commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    def __init__(self, handle, fmt=_DEFAULT_TAB_FORMAT):
From a UI point of view, and without being familiar with Infernal, having a main SearchIO ``format`` argument (here ``infernal-tab`` I believe) and a secondary ``fmt`` argument seems confusing.

Does it make sense to think about ``format="infernal-tab1"``, ``format="infernal-tab2"`` etc?

2024-10-28 14:33 UTC, peterjc commented
Over to @bow to look at...

2024-10-29 19:10 UTC, bow commented
Hey @drs @peterjc Thanks for opening the PR! I'm just writing here to let you know that I am looking into it already ~ it's going to take me a while to go through the whole thing and I hope within the next 1-2 weeks I'll be able to reply more thoroughly.

2025-01-06 06:22 UTC, bow requested changes
@drs Thank you again for opening this PR ~ impressive work! I am sorry it took me this long to get back to you.

I have added some comments / suggestions. There's only one minor typo that I'd like you to fix (the reason this is marked as 'request changes'). Most of the comments are suggestions and and questions about the code. So feel free to do what you think is best for those (including keeping current behavior).

2025-01-06 06:22 UTC, bow commented on Bio/SearchIO/InfernalIO/infernal_text.py
> +import operator
Style suggestion (feel free to ignore):

```suggestion
import operator
import re
```

2025-01-06 06:22 UTC, bow commented on Bio/SearchIO/InfernalIO/infernal_text.py
> +                self.line = read_forward(self.handle)
Also a style suggestion, since the `else` is redundant:

```suggestion
            if not self.line or bool_func(self.line):
                return
            self.line = read_forward(self.handle)
```

2025-01-17 15:57 UTC, peterjc commented
If you are comfortable doing so, I would suggest rebasing this to the current master branch.

Doing a merge to resolve the conflicts will hinder our typical rebase-and-merge approach. But we could still do a squash-and-merge but that would lose your commit history.

2025-01-18 00:06 UTC, drs commented
I tried to rebase to the current master branch. I'm not very familiar with the process. Hopefully, I did that properly. @peterjc can you confirm if it's fine?

2025-01-18 21:01 UTC, peterjc commented
The rebase looks to have worked, although perhaps not perfectly as there are a few infernal tab tests failing.

2025-01-19 14:44 UTC, drs commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    "trunc": ("truncated", str),
`trunc` can be `no`, `5'`, `3'` or `5’&3'`. Changing the type to `bool` would remove some information. We could create new variables (ex. `5p_trunc` and `3p_trunc`) to keep all the information in a `bool`.

2025-01-19 16:01 UTC, drs commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    def __init__(self, handle, fmt=_DEFAULT_TAB_FORMAT):
That was my plan initially, but it's not straightforward to implement the inference that supports random access (i.e., `InfernalTabIndexer`). To initialize the `SearchIndexer`, we need the `fmt`, so we need to open the file and parse the header before we initialize `SearchIndexer`. My suggestion is to open the file for random access with `_open_for_random_access` from `Bio.File` (as in `SearchIndexer`;  https://github.com/biopython/biopython/blob/dda590d43f7b09eecab40982a4c1ac9fd49fc3b6/Bio/SearchIO/_index.py#L26), read the first two lines and use them to infer the header.

For `InfernalTabParser`, we can simply do: 
- If `fmt` is set, use the `fmt` and ignore the header
- Else read the first two lines of the handle, that should always be the header in a properly formatted file, and infer the header from these lines

I made a tentative update for this proposition in commit 373882b.

2025-01-19 16:03 UTC, drs commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +        self._inclusion_str_to_bool(hsp)
I agree with the suggestion and made this change in commit d0f8bf6.

2025-01-19 16:05 UTC, drs commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    "wfrct2": ("wfrct2", str),
I agree. I changed the behavior in commit 45c8327 and updated documentation in commit 6625e99.

2025-01-21 21:43 UTC, bow commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    def __init__(self, handle, fmt=_DEFAULT_TAB_FORMAT):
The plan looks ok @drs. One comment about the inference logic itself: instead of doing this (paraphrased from code):

```
        if isinstance(fmt, int):
            if not 1 <= fmt <= 3:
                # <raise error>
            self.fmt = fmt
        else:
            self.fmt = <infer>
```

Let's do the check more explicitly (also to make the behavior less surprising):

```
        # The `isinstance` check below allows us to provide a consistent error
        # message, even when e.g. `fmt` happens to be unhashable.
        if isinstance(fmt, int) and fmt in {1, 2, 3}:
            self.fmt = fmt
        elif fmt is None:
            self.fmt = <infer>
        else:
            # raise exception
```

This would, e.g. raise an error when `fmt="1"` or `fmt="tabular-1"`.

2025-01-21 21:44 UTC, bow commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    "trunc": ("truncated", str),
Aha :ok_hand: ~ no need to make a bool then, let's keep it as-is.

2025-01-22 14:25 UTC, drs commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    def __init__(self, handle, fmt=_DEFAULT_TAB_FORMAT):
I suggest that we drop the support for overriding the format and always infer from the header, as it can result in inconsistent behavior in some cases:

- There is no validation of the format when parsing the result rows. In most cases, when the format is incorrect, a `ValueError` (ex. `ValueError: invalid literal for int() with base 10: '-' `) is raised when casting the type in: 

https://github.com/drs/biopython-infernal/blob/f65381b7d54105b3aa9c3f440e1becb879c49966/Bio/SearchIO/InfernalIO/infernal_tab.py#L313-L318

But that's not always the case. If the user sets for format to 1, and the file format is 3, no error is raised, and the `description` will contain the three last columns `mdl len`, `seq len` and `description of target`. 

- Since the file is space separated, and the description can contain spaces, we cannot rely on the number of columns for validation.

2025-02-06 21:02 UTC, drs commented on Bio/SearchIO/InfernalIO/infernal_tab.py
> +    def __init__(self, handle, fmt=_DEFAULT_TAB_FORMAT):
I removed the user-provided `fmt` argument. We still need to set the tabular format of the `InfernalTabParser` in the `InfernalTabIndexer` since the header cannot be passed to the parser. I keep the `fmt` argument as an internal value (now `_fmt`) for the `InfernalTabIndexer`.

2025-03-06 16:50 UTC, drs commented
@peterjc @bow I resolved most comments/suggestions (except contributions, which I will do at the end). I'm not sure that I understand why it's failing `codecov`. It there anything that I must do to address this? Is there anything that needs to be done on my end?

2025-03-07 11:13 UTC, peterjc commented
We're not so strict on the coverage reporting (it is a bit unreliable), but aspire to full coverage.

2025-03-07 11:15 UTC, peterjc commented
There are some git merge conflicts - if you are familiar with it, we would _prefer_ a `git rebase origin/master` to resolve them, rather than merges.

2025-03-09 20:24 UTC, bow commented
I agree with @peterjc ~ let's do a rebase to keep the history linear and clean. I can see the number of changed files in this commit is way too large. After a rebase, the coverage calculation might also be correct (i.e. it shouldn't fail because of files that are not part of the MR).

After the rebase, I don't have anything else from my end :slightly_smiling_face:.

2025-03-15 02:14 UTC, drs commented
@bow @peterjc I did the rebase. Everything looks good. I believe that the PR is ready to be merged.

I added this change to NEWS.rst under the upcoming v1.86.

2025-03-22 05:59 UTC, merged

2025-03-22 06:00 UTC, bow commented
Thank you @drs :tada: ~ I have just rebased this on top of `master` now :slightly_smiling_face:.